atmaq_intel:
  build:
    compiler: intel
    option: -DAPP=ATMAQ -DCCPP_SUITES=FV3_GFS_v16 -D32BIT=ON
    turnoff:
    - s4
  tests:
  - regional_atmaq:
      project:
      - daily
      baseline: 'True'
      turnoff:
      - s4
      resources:
        orion: {ppn: '40', nodes: '7', wlclk: '00:40:00'}
        hera: {ppn: '40', nodes: '7', wlclk: '00:30:00'}
        ursa: {ppn: '192', nodes: '2', wlclk: '00:30:00'}
        derecho: {ppn: '128', nodes: '3', wlclk: '00:30:00'}
        hercules: {ppn: '80', nodes: '4', wlclk: '00:30:00'}
        gaeac6: {ppn: '192', nodes: '2', wlclk: '00:30:00'}
  - regional_atmaq_canopy:
      project:
      - daily
      baseline: 'True'
      turnoff:
      - s4
      resources:
        orion: {ppn: '40', nodes: '7', wlclk: '00:30:00'}
        hera: {ppn: '40', nodes: '7', wlclk: '00:30:00'}
        ursa: {ppn: '192', nodes: '2', wlclk: '00:30:00'}
        derecho: {ppn: '128', nodes: '3', wlclk: '00:30:00'}
        hercules: {ppn: '80', nodes: '4', wlclk: '00:30:00'}
        gaeac6: {ppn: '192', nodes: '2', wlclk: '00:30:00'}
atmaq_debug_intel:
  build:
    compiler: intel
    option: -DAPP=ATMAQ -DCCPP_SUITES=FV3_GFS_v16 -DDEBUG=ON -D32BIT=ON
    turnoff:
    - noaacloud
    - s4
  tests:
  - regional_atmaq_debug:
      project:
      - daily
      baseline: 'True'
      turnoff:
      - s4
      - noaacloud
      resources:
        orion: {ppn: '40', nodes: '7', wlclk: '00:45:00'}
        hera: {ppn: '40', nodes: '7', wlclk: '00:45:00'}
        ursa: {ppn: '192', nodes: '2', wlclk: '00:45:00'}
        derecho: {ppn: '128', nodes: '3', wlclk: '00:45:00'}
        hercules: {ppn: '80', nodes: '4', wlclk: '00:45:00'}
        gaeac6: {ppn: '192', nodes: '2', wlclk: '00:45:00'}
