atmf_atm_fbh_intel:
  build:
    compiler: intel
    option: -DAPP=ATMF -DCCPP_SUITES=FV3_HRRR -D32BIT=ON
    turnoff:
    - wcoss2
    - noaacloud
    - acorn
  tests:
  - cpld_regional_atm_fbh:
      project:
      - daily
      baseline: 'True'
      turnoff:
      - wcoss2
      - noaacloud
      - acorn
      resources:
        orion: {ppn: 40, nodes: 1, wlclk: 30}
        hera: {ppn: 40, nodes: 1, wlclk: 30}
        ursa: {ppn: 192, nodes: 1, wlclk: 30}
        derecho: {ppn: 128, nodes: 1, wlclk: 30}
        hercules: {ppn: 80, nodes: 1, wlclk: 30}
        gaeac6: {ppn: 192, nodes: 1, wlclk: 30}
