atmmpas_atm_mpas_dyn32_gnu:
  build:
    compiler: gnu
    option: -DAPP=ATMMPAS -DCCPP_SUITES=MPAS_RRFS -D32BIT=ON
    turnon:
    - hera
    - hercules
  tests:
  - control_gfs_mpas:
      project:
      - daily
      baseline: 'True'
      turnon:
      - hera
      - hercules
      resources:
        orion: {ppn: 40, nodes: 1, wlclk: 30}
        hera: {ppn: 40, nodes: 1, wlclk: 30}
        ursa: {ppn: 192, nodes: 1, wlclk: 30}
        derecho: {ppn: 128, nodes: 1, wlclk: 30}
        hercules: {ppn: 80, nodes: 1, wlclk: 30}
        gaeac6: {ppn: 192, nodes: 1, wlclk: 30}
