atmw_intel:
  build:
    compiler: intel
    option: -DAPP=ATMW -DCCPP_SUITES=FV3_GFS_v17_p8 -D32BIT=ON
    turnoff:
    - wcoss2
  tests:
  - atmwav_control_noaero_p8:
      project:
      - daily
      baseline: 'True'
      turnoff:
      - wcoss2
      resources:
        orion: {ppn: '40', nodes: '5', wlclk: '00:30:00'}
        hera: {ppn: '40', nodes: '5', wlclk: '00:30:00'}
        ursa: {ppn: '192', nodes: '1', wlclk: '00:30:00'}
        derecho: {ppn: '128', nodes: '2', wlclk: '00:30:00'}
        hercules: {ppn: '80', nodes: '3', wlclk: '00:30:00'}
        gaeac6: {ppn: '192', nodes: '1', wlclk: '00:30:00'}
