hafsw_intel:
  build:
    compiler: intel
    option: -DAPP=HAFSW -DMOVING_NEST=ON -DCCPP_SUITES=FV3_HAFS_v1_gfdlmp_tedmf,FV3_HAFS_v1_gfdlmp_tedmf_nonsst,FV3_HAFS_v1_thompson_tedmf_gfdlsf,FV3_global_nest_v1,FV3_HAFS_v1_gfdlmpv3_tedmf
      -D32BIT=ON
  tests:
  - hafs_regional_atm:
      project:
      - daily
      baseline: 'True'
      resources:
        orion: {ppn: '40', nodes: '15', wlclk: '00:30:00'}
        hera: {ppn: '40', nodes: '15', wlclk: '00:30:00'}
        ursa: {ppn: '192', nodes: '4', wlclk: '00:30:00'}
        derecho: {ppn: '128', nodes: '5', wlclk: '00:30:00'}
        hercules: {ppn: '80', nodes: '8', wlclk: '00:30:00'}
        gaeac6: {ppn: '192', nodes: '4', wlclk: '00:30:00'}
  - hafs_regional_atm_gfdlmpv3:
      project:
      - daily
      baseline: 'True'
      resources:
        orion: {ppn: '40', nodes: '15', wlclk: '00:30:00'}
        hera: {ppn: '40', nodes: '15', wlclk: '00:30:00'}
        ursa: {ppn: '192', nodes: '4', wlclk: '00:30:00'}
        derecho: {ppn: '128', nodes: '5', wlclk: '00:30:00'}
        hercules: {ppn: '80', nodes: '8', wlclk: '00:30:00'}
        gaeac6: {ppn: '192', nodes: '4', wlclk: '00:30:00'}
  - hafs_regional_atm_thompson_gfdlsf:
      project:
      - daily
      baseline: 'True'
      resources:
        orion: {ppn: '40', nodes: '15', wlclk: '00:30:00'}
        hera: {ppn: '40', nodes: '15', wlclk: '00:30:00'}
        ursa: {ppn: '192', nodes: '4', wlclk: '00:30:00'}
        derecho: {ppn: '128', nodes: '5', wlclk: '00:30:00'}
        hercules: {ppn: '80', nodes: '8', wlclk: '00:30:00'}
        gaeac6: {ppn: '192', nodes: '4', wlclk: '00:30:00'}
  - hafs_regional_atm_wav:
      project:
      - daily
      baseline: 'True'
      resources:
        orion: {ppn: '40', nodes: '9', wlclk: '00:30:00'}
        hera: {ppn: '40', nodes: '9', wlclk: '00:30:00'}
        ursa: {ppn: '192', nodes: '2', wlclk: '00:50:00'}
        derecho: {ppn: '128', nodes: '3', wlclk: '00:30:00'}
        hercules: {ppn: '80', nodes: '5', wlclk: '00:30:00'}
        gaeac6: {ppn: '192', nodes: '2', wlclk: '00:30:00'}
  - hafs_regional_1nest_atm:
      project:
      - daily
      baseline: 'True'
      turnoff:
      - s4
      - noaacloud
      resources:
        orion: {ppn: '40', nodes: '9', wlclk: '00:30:00'}
        hera: {ppn: '40', nodes: '9', wlclk: '00:30:00'}
        ursa: {ppn: '192', nodes: '2', wlclk: '00:30:00'}
        derecho: {ppn: '128', nodes: '3', wlclk: '00:30:00'}
        hercules: {ppn: '80', nodes: '5', wlclk: '00:30:00'}
        gaeac6: {ppn: '192', nodes: '2', wlclk: '00:30:00'}
  - hafs_regional_telescopic_2nests_atm:
      project:
      - daily
      baseline: 'True'
      turnoff:
      - s4
      - noaacloud
      resources:
        orion: {ppn: '40', nodes: '12', wlclk: '00:30:00'}
        hera: {ppn: '40', nodes: '12', wlclk: '00:30:00'}
        ursa: {ppn: '192', nodes: '3', wlclk: '00:30:00'}
        derecho: {ppn: '128', nodes: '4', wlclk: '00:30:00'}
        hercules: {ppn: '80', nodes: '6', wlclk: '00:30:00'}
        gaeac6: {ppn: '192', nodes: '3', wlclk: '00:30:00'}
  - hafs_global_1nest_atm:
      project:
      - daily
      baseline: 'True'
      turnoff:
      - s4
      - noaacloud
      resources:
        orion: {ppn: '40', nodes: '12', wlclk: '00:30:00'}
        hera: {ppn: '40', nodes: '12', wlclk: '00:30:00'}
        ursa: {ppn: '192', nodes: '3', wlclk: '00:30:00'}
        derecho: {ppn: '128', nodes: '4', wlclk: '00:30:00'}
        hercules: {ppn: '80', nodes: '6', wlclk: '00:30:00'}
        gaeac6: {ppn: '192', nodes: '3', wlclk: '00:30:00'}
  - hafs_global_multiple_4nests_atm:
      project:
      - daily
      baseline: 'True'
      turnoff:
      - s4
      - noaacloud
      resources:
        orion: {ppn: '40', nodes: '21', wlclk: '00:30:00'}
        hera: {ppn: '40', nodes: '21', wlclk: '00:30:00'}
        ursa: {ppn: '192', nodes: '5', wlclk: '00:30:00'}
        derecho: {ppn: '128', nodes: '7', wlclk: '00:30:00'}
        hercules: {ppn: '80', nodes: '11', wlclk: '00:30:00'}
        gaeac6: {ppn: '192', nodes: '5', wlclk: '00:30:00'}
  - hafs_regional_specified_moving_1nest_atm:
      project:
      - daily
      baseline: 'True'
      turnoff:
      - s4
      - noaacloud
      resources:
        orion: {ppn: '40', nodes: '9', wlclk: '00:30:00'}
        hera: {ppn: '40', nodes: '9', wlclk: '00:30:00'}
        ursa: {ppn: '192', nodes: '2', wlclk: '00:30:00'}
        derecho: {ppn: '128', nodes: '3', wlclk: '00:30:00'}
        hercules: {ppn: '80', nodes: '5', wlclk: '00:30:00'}
        gaeac6: {ppn: '192', nodes: '2', wlclk: '00:30:00'}
  - hafs_regional_storm_following_1nest_atm:
      project:
      - daily
      baseline: 'True'
      turnoff:
      - s4
      - noaacloud
      resources:
        orion: {ppn: '40', nodes: '9', wlclk: '00:30:00'}
        hera: {ppn: '40', nodes: '9', wlclk: '00:30:00'}
        ursa: {ppn: '192', nodes: '2', wlclk: '00:30:00'}
        derecho: {ppn: '128', nodes: '3', wlclk: '00:30:00'}
        hercules: {ppn: '80', nodes: '5', wlclk: '00:30:00'}
        gaeac6: {ppn: '192', nodes: '2', wlclk: '00:30:00'}
  - hafs_global_storm_following_1nest_atm:
      project:
      - daily
      baseline: 'True'
      turnoff:
      - s4
      - noaacloud
      resources:
        orion: {ppn: '40', nodes: '12', wlclk: '00:30:00'}
        hera: {ppn: '40', nodes: '12', wlclk: '00:30:00'}
        ursa: {ppn: '192', nodes: '3', wlclk: '00:30:00'}
        derecho: {ppn: '128', nodes: '4', wlclk: '00:30:00'}
        hercules: {ppn: '80', nodes: '6', wlclk: '00:30:00'}
        gaeac6: {ppn: '192', nodes: '3', wlclk: '00:30:00'}
  - gnv1_nested:
      project:
      - daily
      baseline: 'True'
      turnoff:
      - hercules
      - wcoss2
      - s4
      - noaacloud
      resources:
        orion: {ppn: '40', nodes: '6', wlclk: '00:30:00'}
        hera: {ppn: '40', nodes: '6', wlclk: '00:30:00'}
        ursa: {ppn: '192', nodes: '2', wlclk: '00:30:00'}
        derecho: {ppn: '128', nodes: '2', wlclk: '00:30:00'}
        hercules: {ppn: '80', nodes: '3', wlclk: '00:30:00'}
        gaeac6: {ppn: '192', nodes: '2', wlclk: '00:30:00'}
