hafs-all_hafs_all_intel:
  build:
    compiler: intel
    option: -DAPP=HAFS-ALL -DCCPP_SUITES=FV3_HAFS_v1_gfdlmp_tedmf,FV3_HAFS_v1_gfdlmp_tedmf_nonsst
      -D32BIT=ON
    turnoff:
    - noaacloud
  tests:
  - hafs_regional_docn:
      project:
      - daily
      baseline: 'True'
      turnoff:
      - noaacloud
      resources:
        orion: {ppn: '40', nodes: '9', wlclk: '00:30:00'}
        hera: {ppn: '40', nodes: '9', wlclk: '00:30:00'}
        ursa: {ppn: '192', nodes: '2', wlclk: '00:30:00'}
        derecho: {ppn: '128', nodes: '3', wlclk: '00:30:00'}
        hercules: {ppn: '80', nodes: '5', wlclk: '00:30:00'}
        gaeac6: {ppn: '192', nodes: '2', wlclk: '00:30:00'}
  - hafs_regional_docn_oisst:
      project:
      - daily
      baseline: 'True'
      turnoff:
      - noaacloud
      resources:
        orion: {ppn: '40', nodes: '9', wlclk: '00:30:00'}
        hera: {ppn: '40', nodes: '9', wlclk: '00:30:00'}
        ursa: {ppn: '192', nodes: '2', wlclk: '00:30:00'}
        derecho: {ppn: '128', nodes: '3', wlclk: '00:30:00'}
        hercules: {ppn: '80', nodes: '5', wlclk: '00:30:00'}
        gaeac6: {ppn: '192', nodes: '2', wlclk: '00:30:00'}
