hafs-all_hafs_all_intel:
  build:
    compiler: intel
    option: -DAPP=HAFS-ALL -DCCPP_SUITES=FV3_HAFS_v1_gfdlmp_tedmf,FV3_HAFS_v1_gfdlmp_tedmf_nonsst
      -D32BIT=ON
    turnoff:
    - noaacloud
  tests:
  - hafs_regional_docn:
      project:
      - daily
      baseline: 'True'
      turnoff:
      - noaacloud
      resources:
        orion: {ppn: 40, nodes: 9, wlclk: 30}
        hera: {ppn: 40, nodes: 9, wlclk: 30}
        ursa: {ppn: 192, nodes: 2, wlclk: 30}
        derecho: {ppn: 128, nodes: 3, wlclk: 30}
        hercules: {ppn: 80, nodes: 5, wlclk: 30}
        gaeac6: {ppn: 192, nodes: 2, wlclk: 30}
  - hafs_regional_docn_oisst:
      project:
      - daily
      baseline: 'True'
      turnoff:
      - noaacloud
      resources:
        orion: {ppn: 40, nodes: 9, wlclk: 30}
        hera: {ppn: 40, nodes: 9, wlclk: 30}
        ursa: {ppn: 192, nodes: 2, wlclk: 30}
        derecho: {ppn: 128, nodes: 3, wlclk: 30}
        hercules: {ppn: 80, nodes: 5, wlclk: 30}
        gaeac6: {ppn: 192, nodes: 2, wlclk: 30}
  - hafs_regional_datm_cdeps:
      project:
      - daily
      baseline: 'True'
      turnoff:
      - s4
      - noaacloud
      resources:
        orion: {ppn: 40, nodes: 3, wlclk: 30}
        hera: {ppn: 40, nodes: 3, wlclk: 30}
        ursa: {ppn: 192, nodes: 1, wlclk: 30}
        derecho: {ppn: 128, nodes: 1, wlclk: 30}
        hercules: {ppn: 80, nodes: 2, wlclk: 30}
        gaeac6: {ppn: 192, nodes: 1, wlclk: 30}
