ng-godas_datm_cdeps_intel:
  build:
    compiler: intel
    option: -DAPP=NG-GODAS
    turnoff:
    - wcoss2
  tests:
  - datm_cdeps_control_cfsr:
      project:
      - daily
      baseline: 'True'
      turnoff:
      - wcoss2
      resources:
        orion: {ppn: '40', nodes: '1', wlclk: '00:30:00'}
        hera: {ppn: '40', nodes: '1', wlclk: '00:30:00'}
        ursa: {ppn: '192', nodes: '1', wlclk: '00:30:00'}
        derecho: {ppn: '128', nodes: '1', wlclk: '00:30:00'}
        hercules: {ppn: '80', nodes: '1', wlclk: '00:30:00'}
        gaeac6: {ppn: '192', nodes: '1', wlclk: '00:30:00'}
  - datm_cdeps_restart_cfsr:
      project:
      - daily
      dependency: datm_cdeps_control_cfsr
      turnoff:
      - wcoss2
      - noaacloud
      resources:
        orion: {ppn: '40', nodes: '1', wlclk: '00:30:00'}
        hera: {ppn: '40', nodes: '1', wlclk: '00:30:00'}
        ursa: {ppn: '192', nodes: '1', wlclk: '00:30:00'}
        derecho: {ppn: '128', nodes: '1', wlclk: '00:30:00'}
        hercules: {ppn: '80', nodes: '1', wlclk: '00:30:00'}
        gaeac6: {ppn: '192', nodes: '1', wlclk: '00:30:00'}
  - datm_cdeps_control_gefs:
      project:
      - daily
      baseline: 'True'
      turnoff:
      - wcoss2
      resources:
        orion: {ppn: '40', nodes: '1', wlclk: '00:30:00'}
        hera: {ppn: '40', nodes: '1', wlclk: '00:30:00'}
        ursa: {ppn: '192', nodes: '1', wlclk: '00:30:00'}
        derecho: {ppn: '128', nodes: '1', wlclk: '00:30:00'}
        hercules: {ppn: '80', nodes: '1', wlclk: '00:30:00'}
        gaeac6: {ppn: '192', nodes: '1', wlclk: '00:30:00'}
  - datm_cdeps_iau_gefs:
      project:
      - daily
      baseline: 'True'
      turnoff:
      - wcoss2
      resources:
        orion: {ppn: '40', nodes: '1', wlclk: '00:30:00'}
        hera: {ppn: '40', nodes: '1', wlclk: '00:30:00'}
        ursa: {ppn: '192', nodes: '1', wlclk: '00:30:00'}
        derecho: {ppn: '128', nodes: '1', wlclk: '00:30:00'}
        hercules: {ppn: '80', nodes: '1', wlclk: '00:30:00'}
        gaeac6: {ppn: '192', nodes: '1', wlclk: '00:30:00'}
  - datm_cdeps_stochy_gefs:
      project:
      - daily
      baseline: 'True'
      turnoff:
      - wcoss2
      resources:
        orion: {ppn: '40', nodes: '1', wlclk: '00:30:00'}
        hera: {ppn: '40', nodes: '1', wlclk: '00:30:00'}
        ursa: {ppn: '192', nodes: '1', wlclk: '00:30:00'}
        derecho: {ppn: '128', nodes: '1', wlclk: '00:30:00'}
        hercules: {ppn: '80', nodes: '1', wlclk: '00:30:00'}
        gaeac6: {ppn: '192', nodes: '1', wlclk: '00:30:00'}
  - datm_cdeps_ciceC_cfsr:
      project:
      - daily
      baseline: 'True'
      turnoff:
      - wcoss2
      - noaacloud
      resources:
        orion: {ppn: '40', nodes: '1', wlclk: '00:30:00'}
        hera: {ppn: '40', nodes: '1', wlclk: '00:30:00'}
        ursa: {ppn: '192', nodes: '1', wlclk: '00:30:00'}
        derecho: {ppn: '128', nodes: '1', wlclk: '00:30:00'}
        hercules: {ppn: '80', nodes: '1', wlclk: '00:30:00'}
        gaeac6: {ppn: '192', nodes: '1', wlclk: '00:30:00'}
  - datm_cdeps_bulk_cfsr:
      project:
      - daily
      baseline: 'True'
      turnoff:
      - wcoss2
      - noaacloud
      resources:
        orion: {ppn: '40', nodes: '1', wlclk: '00:30:00'}
        hera: {ppn: '40', nodes: '1', wlclk: '00:30:00'}
        ursa: {ppn: '192', nodes: '1', wlclk: '00:30:00'}
        derecho: {ppn: '128', nodes: '1', wlclk: '00:30:00'}
        hercules: {ppn: '80', nodes: '1', wlclk: '00:30:00'}
        gaeac6: {ppn: '192', nodes: '1', wlclk: '00:30:00'}
  - datm_cdeps_bulk_gefs:
      project:
      - daily
      baseline: 'True'
      turnoff:
      - wcoss2
      - noaacloud
      resources:
        orion: {ppn: '40', nodes: '1', wlclk: '00:30:00'}
        hera: {ppn: '40', nodes: '1', wlclk: '00:30:00'}
        ursa: {ppn: '192', nodes: '1', wlclk: '00:30:00'}
        derecho: {ppn: '128', nodes: '1', wlclk: '00:30:00'}
        hercules: {ppn: '80', nodes: '1', wlclk: '00:30:00'}
        gaeac6: {ppn: '192', nodes: '1', wlclk: '00:30:00'}
  - datm_cdeps_mx025_cfsr:
      project:
      - daily
      baseline: 'True'
      turnoff:
      - wcoss2
      - noaacloud
      resources:
        orion: {ppn: '40', nodes: '6', wlclk: '00:30:00'}
        hera: {ppn: '40', nodes: '6', wlclk: '00:30:00'}
        ursa: {ppn: '192', nodes: '2', wlclk: '00:30:00'}
        derecho: {ppn: '128', nodes: '2', wlclk: '00:30:00'}
        hercules: {ppn: '80', nodes: '3', wlclk: '00:30:00'}
        gaeac6: {ppn: '192', nodes: '2', wlclk: '00:30:00'}
  - datm_cdeps_mx025_gefs:
      project:
      - daily
      baseline: 'True'
      turnoff:
      - wcoss2
      - noaacloud
      resources:
        orion: {ppn: '40', nodes: '6', wlclk: '00:30:00'}
        hera: {ppn: '40', nodes: '6', wlclk: '00:30:00'}
        ursa: {ppn: '192', nodes: '2', wlclk: '00:30:00'}
        derecho: {ppn: '128', nodes: '2', wlclk: '00:30:00'}
        hercules: {ppn: '80', nodes: '3', wlclk: '00:30:00'}
        gaeac6: {ppn: '192', nodes: '2', wlclk: '00:30:00'}
  - datm_cdeps_multiple_files_cfsr:
      project:
      - daily
      turnoff:
      - wcoss2
      - noaacloud
      resources:
        orion: {ppn: '40', nodes: '1', wlclk: '00:30:00'}
        hera: {ppn: '40', nodes: '1', wlclk: '00:30:00'}
        ursa: {ppn: '192', nodes: '1', wlclk: '00:30:00'}
        derecho: {ppn: '128', nodes: '1', wlclk: '00:30:00'}
        hercules: {ppn: '80', nodes: '1', wlclk: '00:30:00'}
        gaeac6: {ppn: '192', nodes: '1', wlclk: '00:30:00'}
  - datm_cdeps_3072x1536_cfsr:
      project:
      - daily
      baseline: 'True'
      turnoff:
      - wcoss2
      - noaacloud
      resources:
        orion: {ppn: '40', nodes: '1', wlclk: '00:20:00'}
        hera: {ppn: '40', nodes: '1', wlclk: '00:20:00'}
        ursa: {ppn: '192', nodes: '1', wlclk: '00:20:00'}
        derecho: {ppn: '128', nodes: '1', wlclk: '00:20:00'}
        hercules: {ppn: '80', nodes: '1', wlclk: '00:20:00'}
        gaeac6: {ppn: '192', nodes: '1', wlclk: '00:20:00'}
  - datm_cdeps_gfs:
      project:
      - daily
      baseline: 'True'
      turnoff:
      - wcoss2
      - noaacloud
      resources:
        orion: {ppn: '40', nodes: '1', wlclk: '00:30:00'}
        hera: {ppn: '40', nodes: '1', wlclk: '00:30:00'}
        ursa: {ppn: '192', nodes: '1', wlclk: '00:30:00'}
        derecho: {ppn: '128', nodes: '1', wlclk: '00:30:00'}
        hercules: {ppn: '80', nodes: '1', wlclk: '00:30:00'}
        gaeac6: {ppn: '192', nodes: '1', wlclk: '00:30:00'}
ng-godas_datm_cdeps_debug_intel:
  build:
    compiler: intel
    option: -DAPP=NG-GODAS -DDEBUG=ON
    turnoff:
    - wcoss2
    - acorn
    - noaacloud
  tests:
  - datm_cdeps_debug_cfsr:
      project:
      - daily
      baseline: 'True'
      turnoff:
      - wcoss2
      - acorn
      - noaacloud
      resources:
        orion: {ppn: '40', nodes: '1', wlclk: '00:30:00'}
        hera: {ppn: '40', nodes: '1', wlclk: '00:30:00'}
        ursa: {ppn: '192', nodes: '1', wlclk: '00:30:00'}
        derecho: {ppn: '128', nodes: '1', wlclk: '00:30:00'}
        hercules: {ppn: '80', nodes: '1', wlclk: '00:30:00'}
        gaeac6: {ppn: '192', nodes: '1', wlclk: '00:30:00'}
ng-godas_datm_cdeps_intelllvm:
  build:
    compiler: intelllvm
    option: -DAPP=NG-GODAS
    turnon:
    - ursa
  tests:
  - datm_cdeps_control_cfsr:
      project:
      - daily
      baseline: 'True'
      turnon:
      - ursa
      resources:
        orion: {ppn: '40', nodes: '1', wlclk: '00:30:00'}
        hera: {ppn: '40', nodes: '1', wlclk: '00:30:00'}
        ursa: {ppn: '192', nodes: '1', wlclk: '00:30:00'}
        derecho: {ppn: '128', nodes: '1', wlclk: '00:30:00'}
        hercules: {ppn: '80', nodes: '1', wlclk: '00:30:00'}
        gaeac6: {ppn: '192', nodes: '1', wlclk: '00:30:00'}
ng-godas_datm_cdeps_debug_intelllvm:
  build:
    compiler: intelllvm
    option: -DAPP=NG-GODAS -DDEBUG=ON
    turnon:
    - ursa
  tests:
  - datm_cdeps_debug_cfsr:
      project:
      - daily
      baseline: 'True'
      turnon:
      - ursa
      resources:
        orion: {ppn: '40', nodes: '1', wlclk: '00:30:00'}
        hera: {ppn: '40', nodes: '1', wlclk: '00:30:00'}
        ursa: {ppn: '192', nodes: '1', wlclk: '00:30:00'}
        derecho: {ppn: '128', nodes: '1', wlclk: '00:30:00'}
        hercules: {ppn: '80', nodes: '1', wlclk: '00:30:00'}
        gaeac6: {ppn: '192', nodes: '1', wlclk: '00:30:00'}
ng-godas_datm_cdeps_gnu:
  build:
    compiler: gnu
    option: -DAPP=NG-GODAS
    turnon:
    - hera
    - hercules
    - ursa
  tests:
  - datm_cdeps_control_cfsr:
      project:
      - daily
      baseline: 'True'
      turnon:
      - hera
      - hercules
      - ursa
      resources:
        orion: {ppn: '40', nodes: '1', wlclk: '00:30:00'}
        hera: {ppn: '40', nodes: '1', wlclk: '00:30:00'}
        ursa: {ppn: '192', nodes: '1', wlclk: '00:30:00'}
        derecho: {ppn: '128', nodes: '1', wlclk: '00:30:00'}
        hercules: {ppn: '80', nodes: '1', wlclk: '00:30:00'}
        gaeac6: {ppn: '192', nodes: '1', wlclk: '00:30:00'}
