s2swal_intel:
  build:
    compiler: intel
    option: -DAPP=S2SWAL -DCCPP_SUITES=FV3_GFS_v17_coupled_p8,FV3_GFS_v17_coupled_p8_ugwpv1
  tests:
  - cpld_control_p8_lnd:
      project:
      - daily
      baseline: 'True'
      turnoff:
      - noaacloud
      - wcoss2
      resources:
        orion: {ppn: '40', nodes: '9', wlclk: '00:30:00'}
        hera: {ppn: '40', nodes: '9', wlclk: '00:30:00'}
        ursa: {ppn: '192', nodes: '2', wlclk: '00:30:00'}
        derecho: {ppn: '96', nodes: '4', wlclk: '00:30:00'}
        hercules: {ppn: '80', nodes: '5', wlclk: '00:30:00'}
        gaeac6: {ppn: '96', nodes: '4', wlclk: '00:30:00'}
  - cpld_restart_p8_lnd:
      project:
      - daily
      dependency: cpld_control_p8_lnd
      turnoff:
      - noaacloud
      - wcoss2
      resources:
        orion: {ppn: '40', nodes: '9', wlclk: '00:30:00'}
        hera: {ppn: '40', nodes: '9', wlclk: '00:30:00'}
        ursa: {ppn: '192', nodes: '2', wlclk: '00:30:00'}
        derecho: {ppn: '96', nodes: '4', wlclk: '00:30:00'}
        hercules: {ppn: '80', nodes: '5', wlclk: '00:30:00'}
        gaeac6: {ppn: '96', nodes: '4', wlclk: '00:30:00'}
  - cpld_s2sa_p8:
      project:
      - daily
      baseline: 'True'
      turnoff:
      - noaacloud
      resources:
        orion: {ppn: '40', nodes: '5', wlclk: '00:30:00'}
        hera: {ppn: '40', nodes: '5', wlclk: '00:30:00'}
        ursa: {ppn: '192', nodes: '1', wlclk: '00:30:00'}
        derecho: {ppn: '128', nodes: '2', wlclk: '00:30:00'}
        hercules: {ppn: '80', nodes: '3', wlclk: '00:30:00'}
        gaeac6: {ppn: '192', nodes: '1', wlclk: '00:30:00'}
