import yaml
import xml.etree.ElementTree as ET
import os
import re
from typing import Optional

def resolve_env_vars(value: str) -> str:
    if not isinstance(value, str):
        return ""
    pattern = re.compile(r"\$\{(\w+)\}")
    return pattern.sub(lambda m: os.environ.get(m.group(1), m.group(0)), value)

class RocotoXMLBuilder:
    def __init__(self, machine, rt_yaml, baseline_yaml, project=None, filter_tests=None):
        self.machine = machine
        self.project = project
        self.filter_tests = filter_tests
        self.rt_config = rt_yaml if isinstance(rt_yaml, dict) else yaml.safe_load(open(rt_yaml))
        self.baseline_config = yaml.safe_load(open(baseline_yaml))
        self.root = ET.Element("workflow", attrib={
            "realtime": "F",
            "scheduler": "slurm",
            "taskthrottle": "10"
        })

    def _add_cycledef(self):
        ET.SubElement(self.root, "cycledef", name="forecast", start="2025010100", end="2025123100", interval="06:00:00")

    def _add_log(self):
        ET.SubElement(self.root, "log").text = "&LOG;/workflow.log"

    def _add_compile_task(self, key, build):
        compiler = build.get("compiler", "unknown").lower()
        option = build.get("option", "")
        task_name = f"compile_{key}"
        task = ET.SubElement(self.root, "task", name=task_name)
        cmd = f"&PATHRT;/run_compile.sh &PATHRT; &RUNDIR_ROOT; \"{option}\" {key} 2>&1 | tee &LOG;/compile_{key}.log"
        ET.SubElement(task, "command").text = cmd
        ET.SubElement(task, "jobname").text = task_name
        ET.SubElement(task, "account").text = "GFS-DEV"
        ET.SubElement(task, "queue").text = "batch"
        ET.SubElement(task, "partition").text = self.machine
        ET.SubElement(task, "nodes").text = "1"
        ET.SubElement(task, "walltime").text = "00:30:00"
        ET.SubElement(task, "join").text = f"&RUNDIR_ROOT;/compile_{key}.log"
        ET.SubElement(task, "maxtries").text = "2"

    def _add_test_metatask(self, key, tests):
        build = self.rt_config[key]["build"]
        compiler = build.get("compiler", "unknown").lower()
        compile_task = f"compile_{key}"
        metatask = ET.SubElement(self.root, "metatask", name=f"{compile_task}_tests")

        for test in tests:
            for test_name, test_cfg in test.items():
                if self.project and ("project" not in test_cfg or self.project not in test_cfg["project"]):
                    continue
                if self.filter_tests and f"{test_name}_{compiler}" not in self.filter_tests:
                    continue

                ET.SubElement(metatask, "var", name="TEST", value=test_name)
                task = ET.SubElement(metatask, "task", name=test_name)
                cmd = f"&PATHRT;/run_test.sh &PATHRT; &RUNDIR_ROOT; $TEST {key} {compiler} 2>&1 | tee &LOG;/run_{key}.log"
                ET.SubElement(task, "command").text = cmd
                dep = ET.SubElement(task, "dependency")
                ET.SubElement(dep, "taskdep", task=compile_task)
                ET.SubElement(task, "jobname").text = test_name
                ET.SubElement(task, "account").text = "GFS-DEV"
                ET.SubElement(task, "queue").text = "batch"
                ET.SubElement(task, "partition").text = self.machine
                ET.SubElement(task, "nodes").text = "1"
                ET.SubElement(task, "walltime").text = "00:30:00"
                ET.SubElement(task, "join").text = f"&RUNDIR_ROOT;/{key}.log"
                ET.SubElement(task, "maxtries").text = "2"

    def generate(self):
        self.root.insert(0, ET.Comment("Generated by RocotoXMLBuilder"))
        self._add_cycledef()
        self._add_log()
        for key, block in self.rt_config.items():
            self._add_compile_task(key, block.get("build", {}))
            self._add_test_metatask(key, block.get("tests", []))

    def write(self, output_path: str):
        machine_config = self.baseline_config.get(self.machine, {})
        user = os.environ.get("USER", "unknown")

        entity_values = {
            "PATHRT": resolve_env_vars(machine_config.get("PATHRT") or f"/work/noaa/stmp/{user}/UFS-RT"),
            "PATHTR": os.path.dirname(resolve_env_vars(machine_config.get("PATHRT") or f"/work/noaa/stmp/{user}/UFS-RT")),
            "LOG": f"{resolve_env_vars(machine_config.get('PATHRT') or f'/work/noaa/stmp/{user}/UFS-RT')}/logs/log_{self.machine}",
            "RTPWD": resolve_env_vars(machine_config.get("RTPWD") or f"/work/noaa/epic/UFS-WM_RT/NEMSfv3gfs/develop"),
            "INPUTDATA_ROOT": resolve_env_vars(machine_config.get("INPUTDATA_ROOT") or f"/work/noaa/epic/UFS-WM_RT/NEMSfv3gfs/input-data"),
            "INPUTDATA_ROOT_WW3": resolve_env_vars(machine_config.get("INPUTDATA_ROOT_WW3") or f"/work/noaa/epic/UFS-WM_RT/NEMSfv3gfs/input-data/WW3_input_data"),
            "INPUTDATA_ROOT_BMIC": resolve_env_vars(machine_config.get("INPUTDATA_ROOT_BMIC") or f"/work/noaa/epic/UFS-WM_RT/NEMSfv3gfs/BM_IC"),
            "INPUTDATA_LM4": f"{resolve_env_vars(machine_config.get('INPUTDATA_ROOT') or f'/work/noaa/epic/UFS-WM_RT/NEMSfv3gfs/input-data')}/LM4_input_data",
            "RUNDIR_ROOT": resolve_env_vars(machine_config.get("RUNDIR_ROOT") or f"/work/noaa/stmp/{user}/rundir"),
            "NEW_BASELINE": resolve_env_vars(machine_config.get("NEW_BASELINE") or f"/work/noaa/stmp/{user}/FV3_RT/REGRESSION_TEST")
        }

        entity_lines = [f'  <!ENTITY {k} "{v}">' for k, v in entity_values.items() if v]
        doctype = "<!DOCTYPE workflow [\n" + "\n".join(entity_lines) + "\n]>"

        self._indent(self.root)
        xml_str = ET.tostring(self.root, encoding="unicode")
        with open(output_path, "w") as f:
            f.write('<?xml version="1.0" encoding="utf-8"?>\n')
            f.write(doctype + "\n")
            f.write(xml_str)

    def _indent(self, elem, level=0):
        i = "\n" + level * "  "
        if len(elem):
            if not elem.text or not elem.text.strip():
                elem.text = i + "  "
            for child in elem:
                self._indent(child, level + 1)
            if not elem.tail or not elem.tail.strip():
                elem.tail = i
        else:
            if level and (not elem.tail or not elem.tail.strip()):
                elem.tail = i
